[[redirects]]
  from = "/data/success/"
  force = true
  headers = {X-From = "Netlify"}
  to = "https://pua.puanj.com/data/success/success.html"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "https://pua.puanj.com/pages/404.html" #-change-path-here-and-delete-this-comment
  status = 404
